---
- name: Ensure UFW is installed
  apt: name=ufw state=present

- name: Set UFW logging
  ufw: logging=on

- name: Set default firewall to deny
  ufw: state=enabled policy=deny log=yes

- name: Allow SSH
  ufw: rule=allow port=22 proto=tcp

- name: Allow HTTP(S)
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 80
    - 443