---
- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
  args:
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart SSH

- name: Disallow root login via SSH
  lineinfile: dest=/etc/ssh/sshd_config
  args:
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart SSH
