---
- name: Install PHP Dependencies
  apt: name={{ item }} state=present
  with_items:
    - 'php5'
    - 'php-pear'
    - 'php5-common'
    - 'php5-gd'
    - 'php5-cli'
    - 'php5-mcrypt'
    - 'php5-imagick'
    - 'php5-curl'
    - 'php5-dev'
    - 'php5-mysql'
    - 'libapache2-mod-php5'

- name: Debug Vars
  include_vars: php-devel.yml
  when: debug_mode

- name: Medium Memory Vars
  include_vars: medium-memory.yml
  when: ansible_memtotal_mb < 1024 and ansible_memtotal_mb > 400

- name: High Memory Vars
  include_vars: high-memory.yml
  when: ansible_memtotal_mb > 1024

- name: Configure Apache php.ini
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini
