---
- name: Install MySQL
  apt: name={{ item }} state=present
  with_items:
    - 'mysql-server-5.5'
    - 'mysql-server'

- name: Install MySQL Python extension for Ansible
  apt: name=python-mysqldb state=present

- include: mysql-secure.yml
